name: flutter_themez
description: A simple wrapper for Flutter's ThemeData. Including "light" and "dark".
version: 5.0.0
repository: https://github.com/mj12358/flutter-themez
screenshots:
  - description: Flutter Themez Thumbnail
    path: assets/thumbnail.png
funding:
  - https://www.buymeacoffee.com/mj12358
topics:
  - flutter
  - theme

environment:
  sdk: ">=3.13.2 <4.0.0"
  flutter: ">=3.47.2"

dependencies:
  flutter:
    sdk: flutter
  material_ui: 1.2.0

dev_dependencies:
  dart_lintz: 2.2.0
  flutter_test:
    sdk: flutter
