name: Publish to pub.dev

on:
  push:
    paths:
      - 'CHANGELOG.md'
  workflow_dispatch:

jobs:
  publish:

    permissions:
       id-token: write # Required for authentication using OIDC
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Read pubspec.yaml
        id: pubspec
        uses: nichmor/minimal-read-yaml@v0.0.2
        with:
          config: "./pubspec.yaml"

      - name: Get Release Notes
        id: release_notes
        uses: kiyoon/parse-changelog-action@v1
        with:
          changelog-file-path: CHANGELOG.md
          version: ${{ steps.pubspec.outputs['version'] }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # flutter-version: ${{ steps.pubspec.outputs['environment.flutter'] }}

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
        
      - name: Get pub.dev credentials
        uses: flutter-actions/setup-pubdev-credentials@v1

      - name: Check Publish Warnings
        run: flutter pub publish --dry-run

      - name: Publish Package
        run: flutter pub publish -f

      - name: Create Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.pubspec.outputs['version'] }}
          commit: ${{ github.sha }}
          body: ${{ steps.release_notes.outputs.body }}
