name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # tag-pattern on pub.dev: 'v{{version}}'

jobs:
  publish:

    permissions:
      contents: write # Required to update releases
      id-token: write # Required for authentication using OIDC
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Read pubspec.yaml
        id: pubspec
        uses: nichmor/minimal-read-yaml@v0.0.2
        with:
          config: "./pubspec.yaml"

      - name: Get Release Notes
        id: release_notes
        uses: kiyoon/parse-changelog-action@v1
        with:
          changelog-file-path: CHANGELOG.md
          version: ${{ steps.pubspec.outputs['version'] }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run Tests
        run: flutter test
        
      - name: Get pub.dev Credentials
        uses: flutter-actions/setup-pubdev-credentials@v1

      - name: Check Publish Warnings
        run: flutter pub publish --dry-run

      - name: Publish Package
        run: flutter pub publish -f

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.pubspec.outputs['version'] }}
          commit: ${{ github.sha }}
          body: ${{ steps.release_notes.outputs.body }}
